[package]
name = "smid_lcsk_poa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = ">=0.4, <0.7"
fxhash = "0.2"
rand = ">=0.7.3, < 0.9"
itertools = "0.8.2"